# Generated by Django 3.2.25 on 2024-05-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='website',
        ),
    ]
